"""estructura tabla clipboards

Revision ID: a442bd93fb50
Revises: 
Create Date: 2020-09-19 21:12:13.784275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a442bd93fb50'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clipboards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=3), nullable=False),
    sa.Column('text', sa.String(length=8000), nullable=False),
    sa.Column('expire', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clipboards')
    # ### end Alembic commands ###
